### ISSUE TITLE
How can I use it run Kitti dataset

### ISSUE THREAD

**Issue by Carolyn0822** [yichen928/STRL#9]
I found it  rank2  with kitti dataset,but i can't find something about kitti in your code.

**Comment by yichen928** [comment]
Hi, thanks for your interest.

Our KITTI result is evaluated on the _val set_ instead of the _test set_, which is clearly specified in our paper. Thus, STRL should not join the KITTI leaderboard. Actually, I do not know who made this misleading edit on paperwithcode website, since everyone can edit it...

I am sorry that I lose access to the server with KITTI code due to my graduation. However, I think it can be reproduced easily if you are interested. We just modify the network and dataloader in OpenPCDet, and then plug them into our code.
